# Generated by Django 3.0.4 on 2020-03-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='nom',
            new_name='name',
        ),
    ]
