# Generated by Django 3.0.4 on 2020-03-29 14:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
                ('characters', models.ManyToManyField(related_name='novellas', to='characters.Character', verbose_name='list of characters')),
                ('tags', models.ManyToManyField(to='novellas.Tag', verbose_name='list of tags')),
            ],
        ),
    ]
