# Generated by Django 3.0.4 on 2020-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
    ]
