# Generated by Django 3.0.4 on 2020-03-29 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novellas', '0002_auto_20200329_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novella',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
